server:
  port: 8089
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace
spring:
  banner:
    location: classpath:banner.txt
  application:
      name: spring-example
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hy_zhsq_cloud?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password: 123456789
    timeout: 10000 #连接超时 毫秒
    jedis:
      pool:
        max-active: 8
        max-wait: -1 #连接池最大等行时间 -1没有限制
        max-idle: 8
        min-idle: 0
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/**/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: true
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
#jeecg专用配置
minidao:
  base-package: org.jeecg.modules.jmreport.*
  #DB类型（mysql | postgresql | oracle | sqlserver| other）
  db-type: mysql
jeecg:
  # 是否启用安全模式
  safeMode: false
  # 签名密钥串(前后端要一致，正式发布请自行修改)
  signatureSecret: dd05f1c54d63749eda95f9fa6d49v442a
  # 本地：local\Minio：minio\阿里云：alioss
  uploadType: minio
  path:
    #文件上传根目录 设置
    upload: /opt/upFiles
    #webapp文件路径
    webapp: /opt/webapp
  shiro:
    excludeUrls: /test/jeecgDemo/demo3,/test/jeecgDemo/redisDemo/**,/category/**,/visual/**,/map/**,/jmreport/bigscreen2/**
  # minio文件上传
  minio:
    minio_url:  www.xazhsq.cn
    minio_name: minioadmin
    minio_pass: minioadmin
    bucketName: capture
  #分布式锁配置
  redisson:
    address: 127.0.0.1:6379
    password:
    type: STANDALONE
    enabled: true
#Mybatis输出sql日志
logging:
  level:
    org.jeecg.modules.system.mapper: INFO
#forest http参数配置
forest:
  bean-id: config
  backend: okhttp3
  max-connections: 1000
  max-route-connections: 500
  timeout: 10000
  connect-timeout: 10000
  ssl-protocol: SSLv3
  log-enabled: true
  log-request: true
  log-response-status: true
  log-response-content: true
  #  forest中静态变量值
  variables:
    # 东方网力的车辆 人脸抓拍 1400 服务信息
    wangLiClientId: 61050000005030000100 #东方网力自己的设备编号
    gatWangLi1400Ip: http://92.163.0.71:14000
    gatWangLi1400ClientId: 61058200000000000010 #在东方网力注册的本平台编号
    gatWangLi1400Username: yuanyang
    gatWangLi1400Password: yuanyang@123456
    # 大华的车辆 人脸抓拍 1400 服务信息
    gatDaHua1400Ip: http://92.166.66.136:9408
    gatDahUa1400ClientId: 61058200000000000001000011
    gatDahUa1400Username: dahua
    gatDahUa1400Password: dahua@123
    # 大华的一标三实数据上传服务信息
    ministriesIp: http://92.166.66.136:9408
    ministriesUsername: dahua
    ministriesPassword: dahua@123
